### ISSUE TITLE
How can I uninstall this add on completely?

### ISSUE THREAD

**Issue by minovermax** [medhachaitanya/Pure-Battery-Analytics#1]
Even though I have uninstalled this add on through the Apps settings, the tray add on still shows up. How can I uninstall this add on completely?

**Comment by medhachaitanya** [comment]
Thank you for posting. Seems like a bug. I will look in to this. 
Meanwhile, if you would like to get rid of the add-on, please proceed by manually removing the files after uninstalling. 

![issue](https://user-images.githubusercontent.com/7921068/73375210-7343d700-4289-11ea-90f3-26d9097d1d6f.PNG)

Make sure, you have closed the application before deleting the files, by right clicking on the app and choosing exit.

**Comment by minovermax** [comment]
Problem solved! Thank you :)
