### ISSUE TITLE
Pure Battery App Dependency

### ISSUE THREAD

**Issue by udegbunamchuks** [medhachaitanya/Pure-Battery-Analytics#10]
Thanks for the app. I really need a battery app to monitor hen my battery is full and when it has depleted to a certain level.

Please do we need to have the main Pure Battery app installed for this add-on to work?

Also my configuration is set at 20,30,90,100 BUT I still get notifications outside of these numbers. Is there a reason why?

Thanks

**Comment by medhachaitanya** [comment]
You do not require the main app to be installed. Please note that the main app has the features that you wanted like the depletion % etc.

You should not receive notifications other than what you have set from the add on application. However, you might get notifications from the main app. You can turn them off by going to the settings. 

Thanks.  Please let me know if you need any help or have further questions.

**Comment by udegbunamchuks** [comment]
Thanks a lot. Will let you know if anything else comes up
