### ISSUE TITLE
Impressive

### ISSUE THREAD

**Issue by rickballard** [medhachaitanya/Pure-Battery-Analytics#12]
Pure Battery Icon and Analytics is very impressive and useful.  I will donate.  Some observations:
1. Display Font should default to system font for the date/time
2. Option needed to match the icon for battery used by stylus apps
3. Option needed to replace the icon used by stylus apps, e.g. Lenovo's, with a Pure version of same, but which updates periodically, not just when the stylus is used = Lenovo's fail
4. Ability to move the system tray icon/text further to the right nearer the vendor's default position for battery indicator, next to date/time
5. Horizontal, lying down, battery icons work better and can be larger and easier to read
6. Lightning bolt outline, over battery icon, should indicate charging, and flashing red fill colour should indicate low battery, by default
7. A new and different app icon is needed if you want to create app launcher, from the system tray, preferably with a vertical stack of apps rising up from this new icon when this new icon is selected.  Dont bundle this functionality into a battery icon app.
8. The UI for the app should be styled more like a Windows native app, it looks too much like the labels I made for my nasty home made wine.
9. The analytics are awesome, and they deserve a lot of thought on presentation dashboarding. 
10.  A battery life prediction model would be useful, with appropriate disclaimers, which updates based on cummulative usage behaviour. 
11. A Screenshot/bug/comment sender form might also be a great option, as I can't get GitHub to attach an image here, apologies

**Comment by medhachaitanya** [comment]
Thank you so much, Rick. These are good improvements to the app.

**Comment by medhachaitanya** [comment]
I have worked on some of the features. Looking forward to release them by the end of this week.

**Comment by rickballard** [comment]
You are awesome
