### ISSUE TITLE
Artifact in Pure Battery Percentage Add-On Settings

### ISSUE THREAD

**Issue by Lord-Memester** [medhachaitanya/Pure-Battery-Analytics#18]
What the window normally looks like:
![image](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/6995d508-aaa5-488a-9270-1db296b2ac08)

What the window looks like when forcibly resized using **[ResizeEnable](http://www.digitallis.co.uk/pc/ResizeEnable/index.html)** (a freeware tool for forcing non-resizable windows to be resized):
![image](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/d11e5169-7628-4f52-9036-56ec95593436)

I noticed the smart outlet control feature hanging around when I was testing the **ResizeEnable** tool. Though I seriously doubt it causes any issues, I cannot imagine the feature is intended to be there. While I am able to enter text into the forms, it also does not seem to work*, which further suggests that it is not intended to be there.

I should add that it is visible no matter what tab is chosen. (Seen below:)
![image](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/e5998658-276f-43bd-a0d4-fef8786ad48b)
![image](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/cc2e68bd-22b4-4fd8-ab4a-700076489a3d)
<sub>*`test@test.test` is a replacement for the actual email address associated with my **TP-Link Kasa** account. I determined that it did not work by using my real email, but changed it in the provided images so as to protect the privacy of my account.<sub>

---
To reproduce this issue:
- I imagine you must be using `Windows 11` or `Windows 10`. I am personally using `Windows 11, version 23H2`.
1. Ensure `Pure Battery Percentage Add-On` is running, and was installed from the Microsoft Store.
2. If not already installed, install [ResizeEnable](http://www.digitallis.co.uk/pc/ResizeEnable/index.html).
3. Open `ResizeEnableRunner.exe`, found in the unzipped folder.
4. Through the right-click menu on the taskbar item, open the `Add-on Settings` for the `Pure Battery Percentage Add-On`.
5. Through the right-click menu on the new ![ResizeEnableRunner2 ico](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/497893f5-9813-46ce-a1b7-b780738ff1be) taskbar icon, `Quit` `ResizeEnableRunner`. *(This is to prevent the `Pure Battery Percentage Add-On Settings` window from resizing properly, as is necessary for stationary capture*<sup>(Note 1)</sup> *of the issue. This does not negate the fact that there is still seemingly unintended content within the program.)*
6. Resize the `Pure Battery Percentage Add-On Settings` window by dragging the right size border out until the window is about 3 to 4 times its original width, or until the previously depicted **TP-Link Kasa** integration settings are visible.

<sub>Note 1: you can skip step 5 and move on to step 6 if you are satisfied with seeing the menu only while you are actively adjusting the window size and your `Visual Effects` `Performance Options` in `Windows` have `Show window contents while dragging` enabled. My `Visual Effects` `Performance Options` are depicted below:
![image](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/d49745be-684f-47cb-a38e-bd053c821a5e)</sub>

---
### Enlarged `ResizeEnableRunner.exe` icon: 
![ResizeEnableRunner1 ico](https://github.com/medhachaitanya/Pure-Battery-Analytics/assets/71044282/548d3f45-b436-4ae1-b460-fe5ba1ddaece)

**Comment by medhachaitanya** [comment]
Thanks for sharing. That was smart 😀. It was not intended to be present. I was trying to test some functionality, and I left it as it is and ignored it as the window size restricted its visibility. 

I will take it away. Again, thanks for sharing.

**Comment by Lord-Memester** [comment]
> Thanks for sharing. That was smart 😀. It was not intended to be present. I was trying to test some functionality, and I left it as it is and ignored it as the window size restricted its visibility.
> 
> I will take it away. Again, thanks for sharing.

Happy to help! Love the program, by the way.
