### ISSUE TITLE
The number does not appear on the windows 11 taskbar

### ISSUE THREAD

**Issue by Eddie7344** [medhachaitanya/Pure-Battery-Analytics#5]
Hello!!
Please could you help me, the percentage number does not appear, thank you very much.
See you soon!!
![Captura de pantalla 2021-11-16 135918](https://user-images.githubusercontent.com/94481867/142049199-0576f809-c2cc-48ed-b6cf-08c4615fad81.jpg)

**Comment by medhachaitanya** [comment]
Oh no! I'm not yet on Win 11. Sorry for this issue and thanks for sharing. 
Could you try changing the color of the icon ? You can try it by right clicking on the icon and choosing the add-on settings. Just fiddle with the add-on settings. Please let me know.

**Comment by medhachaitanya** [comment]
![addonsettings](https://user-images.githubusercontent.com/7921068/142072401-6f933bc9-e700-4d48-b42f-6241980bb9c0.png)

Try fiddling the settings highlighted in the image below. I am sorry for asking you to do this. I am not yet on Windows 11.
![addonsettings1](https://user-images.githubusercontent.com/7921068/142072412-6f215f92-7808-43b2-846b-4dc454dd77ca.png)

**Comment by Eddie7344** [comment]
![image](https://user-images.githubusercontent.com/94481867/142079459-20c02830-7fe6-4741-be4f-c1fde532ff70.png)
it's done like that
![image](https://user-images.githubusercontent.com/94481867/142079655-77dc857e-e80e-4941-b131-65a0c07b08bf.png)
with black
Thanks bro!!

**Comment by medhachaitanya** [comment]
Thanks brother. I am glad this temporary quick fix worked. I will work on this issue to make it look much better once I upgrade my laptop to Windows 11.
