### ISSUE TITLE
[Request] Add Bluetooth battery level

### ISSUE THREAD

**Issue by haniag** [medhachaitanya/Pure-Battery-Analytics#6]
Would it be possible to please add the battery level for Bluetooth devices like a headset? Currently, the only way to check that is to go to Windows Settings, and then to Devices to see the battery level there. It would be super if the user can choose which battery level to display in task bar. Thanks.

**Comment by medhachaitanya** [comment]
That's a great suggestion.  I've added this to my to do list.  Hopefully soon.  Thank you.
