### ISSUE TITLE
[Request] Add execution of external applications for different states of batery level.

### ISSUE THREAD

**Issue by WYtransport** [medhachaitanya/Pure-Battery-Analytics#7]
I would be grateful for adding the ability to run an external application for different battery states (from settings). This will enable sending status e-mails as well as switching on the UPS, external power supply, etc. for low but also for charged batteries. Highly sought after options.

**Comment by medhachaitanya** [comment]
Thanks for this feedback. I will see if there's a way to do this. Have a good one!
