### ISSUE TITLE
I don't receive notifications

### ISSUE THREAD

**Issue by GrayLanterns** [medhachaitanya/Pure-Battery-Analytics#9]
for some reason i never receive notifications. i've tried reinstalling the app but it didn't help.
![image](https://user-images.githubusercontent.com/83039148/167401116-908f6051-f785-4418-ab11-c8f87a310597.png)

**Comment by medhachaitanya** [comment]
Can you check if notifications are enabled for this app in the windows settings ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: GrayLanterns ***@***.***>
Sent: Monday, May 9, 2022 7:31:05 AM
To: medhachaitanya/PureBatteryAnalytics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [medhachaitanya/PureBatteryAnalytics] I don't receive notifications (Issue #9)


for some reason i never receive notifications. i've tried reinstalling the app but it didn't help.
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F83039148%2F167401116-908f6051-f785-4418-ab11-c8f87a310597.png&data=05%7C01%7C%7C407d423a40c14a041b8c08da31af67d0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637876926698536259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rvF0xN4yx5gZnRViMwrm3pm1BJWbZj2kUL%2BA%2B5omEa8%3D&reserved=0>

**Comment by medhachaitanya** [comment]
@GrayLanterns Got a chance to try my recommendation ?

Thanks!

**Comment by GrayLanterns** [comment]
> @GrayLanterns Got a chance to try my recommendation ?
> 
> Thanks!

I did but it doesn't send notifications. I've checked the app settings. It has the base permissions to run in the background and notifications are enabled as well.

**Comment by medhachaitanya** [comment]
@GrayLanterns Thanks for checking. Can you also check if Windows is in focus mode ? 
Focus mode suppresses the notifications. Please let me know.

**Comment by GrayLanterns** [comment]
Focus mode is always off. Even then, I've set the app on the priority list, just in case. The app just fails to notify don't know what's the issue

**Comment by GrayLanterns** [comment]
Please help me out as and when you can. Pure Battery is the only trusted app on the Microsoft Store that's capable of handling this problem.

**Comment by medhachaitanya** [comment]
Sure @GrayLanterns. Thanks for the kind words. 

Lets work together on this. Please drop an email to medhachaitanya@outlook.com so that we can schedule a call/google meeting in the next week to look into the issue. 

Alternatively, you share your email and I'll reach out to you.

**Comment by GrayLanterns** [comment]
Is it so that we can only receive notifications on the window mode?

Because as soon as I switch to full screen, the app fails to notify me of upcoming updates. @medhachaitanya

**Comment by medhachaitanya** [comment]
Nope. You don't need to keep the app open.


You may not receive notifications in these cases.

1. Windows is in focus mode.
2. Notifications are turned off in the app settings.
3. App notifications are turned off in the Windows settings.
4. Windows is in battery saver mode.  You can optimize the app by clicking on the highlight recommendations button in the analytics tab of the application.


Please let me know after checking for these settings.

Thanks.

Medha.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by medhachaitanya** [comment]
Sorry, just relaized that you're referring to the add on. 


Please check if 

1. Notifications for this app are enabled in Windows.

2. Windows is not in focus mode. 


Thanks. 

Medha

**Comment by GrayLanterns** [comment]
I do receive notifications, but not when I'm watching something on **full screen**. Example: Netflix, YouTube, and other OTTs.

**Comment by GrayLanterns** [comment]
The app fails to notify anytime the Window is in full screen mode. Doesn't matter where.

**Comment by medhachaitanya** [comment]
Gotcha! Windows suppresses notifications when an application is in full screen mode. Not sure if there's a way to override.  But I'll research and get back to you soon.


Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GrayLanterns** [comment]
Thankyou! I really hope there's a way! I'm usually so engrossed in watching stuff on OTT that I completely forget to unplug the charger. For the same reason I had the app installed at the first place. :)

**Comment by GrayLanterns** [comment]
Hey, I've found a workaround; emailed you the same in case someone comes to you looking for the exact same thing.

**Comment by medhachaitanya** [comment]
For users who might have same question. 
Solution: 
Simply add Pure Battery to the priority list of the apps. 

Here's how you can set it:
Settings > FocusAssist > "when I'm using an app in full screen mode only" and add Pure battery into the priority list.

Thanks @GrayLanterns.
